lifemark/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from main import views
from accounts import views as account_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.home_page, name='home'),
    url(r'^$', views.LifemarkSearchListView.as_view(), name='home'),
    # url(r'^search$', views.search, name='search'),
    url(r'^search$', views.LifemarkSearchListView.as_view(), name='search'),
    # url(r'^new$', views.new_lifemark, name='new'),
    url(r'^new$', views.CreateLifemarkView.as_view(), name='new'),
    # url(r'^update$', views.update_lifemark, name='update'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdateLifemarkView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteLifemarkView.as_view(), name='delete'),
    url(r'^map$', views.show_map, name='show_map'),

    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^anon/$', account_views.test_anon_user_view, name='anon'),

    # url(r'^test$', views.TestListView.as_view(), name='test_list'),
    url(r'^test/$', views.test_view, name='test'),
    url(r'^test_create_user/$', account_views.test_create_user, name='test_create_user'),
    url(r'^test_login/$', views.test_login, name='test_login'),
]

main/models.py
from django.db import models
from django.db.models import Q


class LifemarkManager(models.Manager):
    def get_any_matches_on_any_fields(self, fields, category, state, keywords_str):
        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = ''

        qs = None

        if category:
            qs = self.filter(category=category)
        else:
            qs = self.all()

        if state:
            qs = qs.filter(state=state)

        q_objects = Q()
        if keywords:
            for field in fields:
                for keyword in keywords:
                    q_objects = q_objects | Q(**{f'{field}__contains': keyword})

        return qs.filter(q_objects)

    def get_all_matches_on_any_fields(self, fields, category, state, keywords_str):
        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = ''

        qs = None

        if category:
            qs = self.filter(category=category)
        else:
            qs = self.all()

        if state:
            qs = qs.filter(state=state)

        q_objects = Q()
        if keywords:
            for keyword in keywords:
                q_keyword = Q()
                for field in fields:
                    q_keyword = q_keyword | Q(**{f'{field}__contains': keyword})
                q_objects = q_objects & q_keyword

        return qs.filter(q_objects)

    def get_dued_lifemarks(self, datehour):
        """
        'dued' means expiration date tomorrow
        compare to curr datehour + 1day
        """
        qs = self.filter(state='todo')
        return qs.extra(where=[f"to_timestamp(due_datehour, 'YYYY-MM-DD HH24') <= to_timestamp('{datehour}', 'YYYY-MM-DD HH24') + interval '1 day'"])

    def get_hourly_dued_lifemarks(self, datehour):
        """
        'hourly dued' means expiration 1hour later
        compare to curr datehour + 1hour
        ignore 00hour items: ruled by view logic
        """
        qs = self.filter(state='todo')
        return qs.extra(where=[f"extract(hour from to_timestamp(due_datehour, 'YYYY-MM-DD HH24')) != 0 and to_timestamp(due_datehour, 'YYYY-MM-DD HH24') <= to_timestamp('{datehour}', 'YYYY-MM-DD HH24') + interval '1 hour'"])


class Lifemark(models.Model):
    title = models.TextField()
    link = models.TextField(blank=True, default='')
    category = models.TextField(blank=True, default='')
    state = models.TextField(blank=True, default='')
    due_datehour = models.TextField(blank=True, default='')
    rating = models.TextField(blank=True, default='')
    tags = models.TextField(blank=True, default='')
    desc = models.TextField(blank=True, default='')
    image_url = models.TextField(blank=True, default='')
    cdate = models.DateTimeField(auto_now_add=True)
    udate = models.DateTimeField(auto_now=True)
    c_geo_lat = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    c_geo_lon = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    u_geo_lat = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    u_geo_lon = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    objects = LifemarkManager()

    def __str__(self):
        return f'Lifemark: "{self.id}: {self.title}"'


class TestModel(models.Model):
    title = models.TextField(default=None, null=True)
    category = models.TextField(default='', null=True)
    state = models.TextField(null=True)
    cdate = models.DateTimeField(auto_now_add=True)

main/forms.py
import re
from django import forms
from main.models import Lifemark

CHOICES_STATE = (
    ('', ''),
    ('todo', 'todo'),
    ('working', 'working'),
    ('complete', 'complete'),
)

DATEHOUR_PATTERN = re.compile('\d{4}-\d{2}-\d{2} \d{2}')


class LifemarkForm(forms.models.ModelForm):
    geo_lat = forms.DecimalField(required=False, widget=forms.fields.HiddenInput())
    geo_lon = forms.DecimalField(required=False, widget=forms.fields.HiddenInput())

    class Meta:
        model = Lifemark
        fields = '__all__'
        exclude = ('c_geo_lat', 'c_geo_lon', 'u_geo_lat', 'u_geo_lon',)
        widgets = {
            'title': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter lifemark title',
            }),
            'link': forms.fields.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter related page link',
            }),
            'category': forms.fields.HiddenInput(),
            'state': forms.fields.Select(
                choices=CHOICES_STATE,
                attrs={'class': 'form-control'},
            ),
            'due_datehour': forms.fields.HiddenInput(),
            'rating': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '0 to 5 xs(xxxxx)'
            }),
            'tags': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter multiple tags with space separator'
            }),
            'desc': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'image_url': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter image url'
            }),
        }
        error_messages = {
            'title': {'required': "You need a valid title"}
        }

    def __init__(self, *args, **kwargs):
        super(LifemarkForm, self).__init__(*args, **kwargs)

    def clean_due_datehour(self):
        data = self.cleaned_data['due_datehour']
        if data and not DATEHOUR_PATTERN.match(data):
            raise forms.ValidationError(f"Invalid date hour format: {data}")

        return data

main/views.py
from collections import OrderedDict
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import Lifemark
from .forms import LifemarkForm
from core.models import LifemarkLineSearchData, LifemarkLineListData


DEFAULT_SEARCH_FIELDS = ('title',
                         'link',
                         'category',
                         'state',
                         'rating',
                         'tags',
                         'desc',
                         'image_url')


def get_distinct_categories():
    qset = Lifemark.objects.values('category').distinct()
    category_list = [e['category'] for e in qset]

    if '' not in category_list:
        category_list.append('')

    return sorted(category_list)


@login_required
def home_page(request):
    lifemarks = (Lifemark.objects
                         .order_by('-udate')[:10])
    existing_categories = get_distinct_categories()

    form = LifemarkForm()
    return render(request, 'home.html', {
        'lifemarks': lifemarks,
        'existing_categories': existing_categories,
        'form': form,
    })


@login_required
def search(request):
    param_keyword = request.GET.get('q')
    keywords = param_keyword.split()
    param_fields = request.GET.get('f')
    if param_fields:
        search_fields = param_fields.split()
    else:
        search_fields = ('title',
                         'link',
                         'category',
                         'state',
                         'rating',
                         'tags',
                         'desc',
                         'image_url')

    lifemarks_qs = Lifemark.objects.get_all_matches_on_any_fields(
        search_fields,
        keywords
    ).order_by('-udate')

    page_no = request.GET.get('page', 1)
    paginator = Paginator(lifemarks_qs, 10)
    try:
        page = paginator.page(page_no)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        # fallback to last_page
        page = paginator.page(paginator.num_pages)

    existing_categories = get_distinct_categories()

    form = LifemarkForm()
    return render(request, 'home.html', {
        'lifemarks': page,
        'existing_categories': existing_categories,
        'form': form,
    })


@method_decorator(login_required, name='dispatch')
class LifemarkSearchListView(ListView):
    model = Lifemark
    context_object_name = 'lifemarks'
    template_name = 'home.html'
    paginate_by = 10
    search_fields = DEFAULT_SEARCH_FIELDS

    def get_context_data(self, **kwargs):
        kwargs['existing_categories'] = get_distinct_categories()
        kwargs['form'] = LifemarkForm()

        paged_lifemarks = super().get_context_data()['page_obj']
        kwargs['lifemark_line_data'] = self.get_keywords_lines(
            list(paged_lifemarks),
            self.request.GET.get('q'),
            self.search_fields
        )

        return super().get_context_data(**kwargs)

    def get_queryset(self):
        keywords = self.request.GET.get('q')
        search_category = self.request.GET.get('c')
        search_state = self.request.GET.get('s')

        if keywords or search_category or search_state:
            queryset = Lifemark.objects.get_all_matches_on_any_fields(
                self.search_fields,
                search_category,
                search_state,
                keywords
            ).order_by('-udate')
        else:
            queryset = Lifemark.objects.all().order_by('-udate')
            self.search_by_line = []

        return queryset

    def get_keywords_lines(self, lifemarks, keywords_str, search_fieldnames=None):
        if not search_fieldnames:
            search_fieldnames = ()

        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = []

        search_line_data = OrderedDict()

        for lm in lifemarks:
            line_search_data = []
            for fieldname in search_fieldnames:
                field_lines = getattr(lm, fieldname).split('\r\n')
                for line_no, line in enumerate(field_lines):
                    for keyword in keywords:
                        if line and keyword.lower() in line:
                            match_line_data = LifemarkLineSearchData(fieldname, line_no, line)
                            if match_line_data not in line_search_data:
                                line_search_data.append(match_line_data)

            search_line_data[lm.id] = LifemarkLineListData(lm, line_search_data)

        return search_line_data


def new_lifemark(request):
    if request.method == 'POST':
        form = LifemarkForm(data=request.POST)
        if form.is_valid():
            form.save()

    return redirect(reverse_lazy('home'))


class CreateLifemarkView(CreateView):
    model = Lifemark
    form_class = LifemarkForm
    template_name = 'home.html'
    # below code failed w/ no reason i can catch!
    # success_url = reverse('home')
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.c_geo_lat = form['geo_lat'].value()
        form.instance.c_geo_lon = form['geo_lon'].value()
        form.instance.u_geo_lat = form['geo_lat'].value()
        form.instance.u_geo_lon = form['geo_lon'].value()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # add context data for no-redirect to success_url case
        #   - just like list view
        #     - but can't show prev list here
        #     - only set categories here
        #   - but 'form' is already set automatically by GCBV logic
        kwargs['existing_categories'] = get_distinct_categories()

        return super().get_context_data(**kwargs)

    '''
    def render_to_response(self, context, **response_kwargs):
        # for debug before response
        return super().render_to_response(context, response_kwargs)
        '''


def update_lifemark(request):
    if request.method == 'POST':
        target = Lifemark.objects.get(id=request.POST['id'])
        form = LifemarkForm(data=request.POST, instance=target)
        if form.is_valid():
            form.save()
    return redirect(reverse_lazy('home'))


class UpdateLifemarkView(UpdateView):
    model = Lifemark
    # fields = ('title', 'link', 'category', 'is_complete', 'due_datehour',
    #           'rating', 'tags', 'image_url')
    form_class = LifemarkForm
    template_name = 'home.html'
    # below code failed w/ no reason i can catch!
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.u_geo_lat = form['geo_lat'].value()
        form.instance.u_geo_lon = form['geo_lon'].value()

        return super().form_valid(form)


def show_map(request):
    latitude = request.GET.get('lat')
    longitude = request.GET.get('lon')

    return render(request, 'show_map.html', {
        'latitude': latitude,
        'longitude': longitude,
    })


class DeleteLifemarkView(DeleteView):
    model = Lifemark
    success_url = reverse_lazy('home')


class TestListView(ListView):
    model = Lifemark
    template_name = 'home.html'


class TestUpdateView(UpdateView):
    model = Lifemark


def test_view(request):
    return HttpResponse('<table><tr><td></td><td>title</td><td>0</td><td>aaa keyword</td></tr></table>')


def test_login(request):
    username = request.GET['username']
    password = request.GET['password']
    if not User.objects.filter(username=username).exists():
        User.objects.create_user(
            username=username,
            password=password
        )
    user = authenticate(request, username=username, password=password)
    login(request, user)

    return HttpResponse('create test login session')

main/templates/includes/common_css.html
<style>
#id_btn_top {
    display: none;
    position: fixed;
    bottom: 20px;
    right: 30px;
    z-index: 99;
    font-size: 18px;
    border: none;
    outline: none;
    background-color: red;
    color: white;
    cursor: pointer;
    padding: 15px;
    border-radius: 4px;
}
#id_btn_top:hover {
    background-color: #555;
}
</style>

main/templates/includes/lifemark_detail.html
{% load lifemark_filters imgur_filters %}

{{ lifemark.id }} <button type="button" id="id_detail_btn_del_{{ lifemark.id }}" class="btn btn-primary btn-sm" onclick="del({{ lifemark.id }})">Del</button>
<button type="button" id="id_detail_btn_edit_{{ lifemark.id }}" class="btn btn-primary btn-sm" onclick="edit(event, {{ lifemark.id }})">Edit</button>
<button type="button" id="id_detail_btn_map_{{ lifemark.id }}" class="btn btn-primary btn-sm" onclick="location.href='{% url 'show_map' %}?lat={{ lifemark.c_geo_lat }}&lon={{ lifemark.c_geo_lon }}'">Map</button>
<button type="button" id="id_detail_btn_recent_map_{{ lifemark.id }}" class="btn btn-primary btn-sm" onclick="location.href='{% url 'show_map' %}?lat={{ lifemark.u_geo_lat }}&lon={{ lifemark.u_geo_lon }}'">Recent Map</button>
<button type="button" id="id_detail_btn_copy_{{ lifemark.id }}" class="btn btn-primary btn-sm" onclick="copy_lifemark({{ lifemark.id }})">Copy</button>
<p>Title: 
    <span style="display: none" id="row_{{ lifemark.id }}_title">{{ lifemark.title }}</span>
    <span style="display: none" id="row_{{ lifemark.id }}_link">{{ lifemark.link }}</span>
    {% if lifemark.link %}
        <a href="{{ lifemark.link }}" target="_blank">{{ lifemark.title }}</a>
    {% else %}
        {{ lifemark.title }}
    {% endif %}
</p>
<p>cdate: <span id="row_{{ lifemark.id }}_cdate">{{ lifemark.cdate }}</span></p>
<p>udate: <span id="row_{{ lifemark.id }}_udate">{{ lifemark.udate }}</span></p>
<p>category: <span id="row_{{ lifemark.id }}_category">{{ lifemark.category }}</span></p>
{% lifemark_field lifemark.id 'state' lifemark.state 'State' %}
{% lifemark_field lifemark.id 'due_datehour' lifemark.due_datehour 'Due' %}
{% lifemark_field lifemark.id 'rating' lifemark.rating 'Rating' %}
{% lifemark_field lifemark.id 'tags' lifemark.tags 'Tags' %}
{% if lifemark.desc %}
    <pre id="row_{{ lifemark.id }}_desc">{{ lifemark.desc }}</pre>
{% endif %}
{% if lifemark.image_url %}
    <a href="{{ lifemark.image_url }}" target="_blank"><img src="{{ lifemark.image_url|to_imgur_thumbnail }}"></a>
    <span style="display: none" id="row_{{ lifemark.id }}_image_url">{{ lifemark.image_url }}</span>
{% endif %}

main/templates/includes/lifemark_form.html
{% load lifemark_filters %}

<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_title">Title</label>
    <div class="col-sm-10">{{ form.title }}</div>
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_link">Link</label>
    <div class="col-sm-10">{{ form.link }}</div>
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_category_txt">Category</label>
    <div class="col-sm-10 flex-grow-1">
        <div class="row">
            <div class="col-sm-8">
                <input type="text" class="form-control" id="id_category_txt" placeholder="Enter or select category">
            </div>
            <div class="col-sm-4">
                <select id="id_category_sel" class="form-control">
                    {% for c in existing_categories %}
                        <option value="{{ c }}">{{ c }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    {{ form.category }}
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_state">State</label>
    <div class="col-sm-10 flex-grow-1">{{ form.state }}</div>
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_due_date">Due Date</label>
    <div class="col-sm-10">
        <div class="row">
            <div class="col-sm-8">
                {% if is_update_form %}
                    <input type="text" class="form-control" id="id_update_due_date" placeholder="Choose Date">
                {% else %}
                    <input type="text" class="form-control" id="id_due_date" placeholder="Choose Date">
                {% endif %}
            </div>
            <div class="col-sm-4">
                <select id="id_due_hour" class="form-control">
                    {% for hour in 24|times %}
                        <option value="{{ hour }}">{{ hour }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    {{ form.due_datehour }}
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_rating">Rating</label>
    <div class="col-sm-10 flex-grow-1">{{ form.rating }}</div>
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_tags">Tags</label>
    <div class="col-sm-10 flex-grow-1">{{ form.tags }}</div>
</div>
<div class="form-group form-row">
    <div class="col-sm-12">{{ form.desc }}</div>
</div>
<div class="form-group form-row">
    <label class="col-sm-2 col-form-label" for="id_img_url">Iamge Url</label>
    <div class="col-sm-10 flex-grow-1">{{ form.image_url }}</div>
</div>

main/templates/includes/pagination.html
{% if is_paginated %}
    <nav aria-label="Lifemark pagination">
        <ul class="pagination">
            {% if page_obj.number > 1 %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Fisrt</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">First</span>
                </li>
            {% endif %}

            {% if page_obj.has_previous %}
                <li class="page-item">
                    {% if request.GET.q %}
                        <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">Prev</a>
                    {% else %}
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a>
                    {% endif %}
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Prev</span>
                </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
                {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <span class="page-link">
                            {{ page_num }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        {% if request.GET.q %}
                            <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_num }}">{{ page_num }}</a>
                        {% else %}
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    {% if request.GET.q %}
                        <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">Next</a>
                    {% else %}
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    {% endif %}
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}

            {% if page_obj.number != paginator.num_pages %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Last</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

main/templates/includes/range_pagination.html
{% if is_paginated %}
    {% load proper_paginate %}
    {% load url_replace %}
    <ul class="pagination">
        {% if page_obj.number == 1 %}
            <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' 1 %}">First</a></li>
        {% endif %}
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">Prev</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
        {% endif %}
        {% for i in paginator|proper_paginate:page_obj.number %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link" href="#">{{ i }}</a><span class="sr-only">(current)</span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
        {% if page_obj.number == paginator.num_pages %}
            <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' paginator.num_pages %}">Last</a></li>
        {% endif %}
    </ul>
{% endif %}