lifemark/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from main import views
from accounts import views as account_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.home_page, name='home'),
    url(r'^$', views.LifemarkSearchListView.as_view(), name='home'),
    # url(r'^search$', views.search, name='search'),
    url(r'^search$', views.LifemarkSearchListView.as_view(), name='search'),
    # url(r'^new$', views.new_lifemark, name='new'),
    url(r'^new$', views.CreateLifemarkView.as_view(), name='new'),
    # url(r'^update$', views.update_lifemark, name='update'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdateLifemarkView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteLifemarkView.as_view(), name='delete'),
    url(r'^map$', views.show_map, name='show_map'),

    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^anon/$', account_views.test_anon_user_view, name='anon'),

    # url(r'^test$', views.TestListView.as_view(), name='test_list'),
    url(r'^test/$', views.test_view, name='test'),
    url(r'^test_create_user/$', account_views.test_create_user, name='test_create_user'),
    url(r'^test_login/$', views.test_login, name='test_login'),
]

main/models.py
from django.db import models
from django.db.models import Q


class LifemarkManager(models.Manager):
    def get_any_matches_on_any_fields(self, fields, category, state, keywords_str):
        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = ''

        qs = None

        if category:
            qs = self.filter(category=category)
        else:
            qs = self.all()

        if state:
            qs = qs.filter(state=state)

        q_objects = Q()
        if keywords:
            for field in fields:
                for keyword in keywords:
                    q_objects = q_objects | Q(**{f'{field}__contains': keyword})

        return qs.filter(q_objects)

    def get_all_matches_on_any_fields(self, fields, category, state, keywords_str):
        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = ''

        qs = None

        if category:
            qs = self.filter(category=category)
        else:
            qs = self.all()

        if state:
            qs = qs.filter(state=state)

        q_objects = Q()
        if keywords:
            for keyword in keywords:
                q_keyword = Q()
                for field in fields:
                    q_keyword = q_keyword | Q(**{f'{field}__contains': keyword})
                q_objects = q_objects & q_keyword

        return qs.filter(q_objects)

    def get_dued_lifemarks(self, datehour):
        """
        'dued' means expiration date tomorrow
        compare to curr datehour + 1day
        """
        qs = self.filter(state='todo')
        return qs.extra(where=[f"to_timestamp(due_datehour, 'YYYY-MM-DD HH24') <= to_timestamp('{datehour}', 'YYYY-MM-DD HH24') + interval '1 day'"])

    def get_hourly_dued_lifemarks(self, datehour):
        """
        'hourly dued' means expiration 1hour later
        compare to curr datehour + 1hour
        ignore 00hour items: ruled by view logic
        """
        qs = self.filter(state='todo')
        return qs.extra(where=[f"extract(hour from to_timestamp(due_datehour, 'YYYY-MM-DD HH24')) != 0 and to_timestamp(due_datehour, 'YYYY-MM-DD HH24') <= to_timestamp('{datehour}', 'YYYY-MM-DD HH24') + interval '1 hour'"])


class Lifemark(models.Model):
    title = models.TextField()
    link = models.TextField(blank=True, default='')
    category = models.TextField(blank=True, default='')
    state = models.TextField(blank=True, default='')
    due_datehour = models.TextField(blank=True, default='')
    rating = models.TextField(blank=True, default='')
    tags = models.TextField(blank=True, default='')
    desc = models.TextField(blank=True, default='')
    image_url = models.TextField(blank=True, default='')
    cdate = models.DateTimeField(auto_now_add=True)
    udate = models.DateTimeField(auto_now=True)
    c_geo_lat = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    c_geo_lon = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    u_geo_lat = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    u_geo_lon = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    objects = LifemarkManager()

    def __str__(self):
        return f'Lifemark: "{self.id}: {self.title}"'


class TestModel(models.Model):
    title = models.TextField(default=None, null=True)
    category = models.TextField(default='', null=True)
    state = models.TextField(null=True)
    cdate = models.DateTimeField(auto_now_add=True)

main/forms.py
import re
from django import forms
from main.models import Lifemark

CHOICES_STATE = (
    ('', ''),
    ('todo', 'todo'),
    ('working', 'working'),
    ('complete', 'complete'),
)

DATEHOUR_PATTERN = re.compile('\d{4}-\d{2}-\d{2} \d{2}')


class LifemarkForm(forms.models.ModelForm):
    geo_lat = forms.DecimalField(required=False, widget=forms.fields.HiddenInput())
    geo_lon = forms.DecimalField(required=False, widget=forms.fields.HiddenInput())

    class Meta:
        model = Lifemark
        fields = '__all__'
        exclude = ('c_geo_lat', 'c_geo_lon', 'u_geo_lat', 'u_geo_lon',)
        widgets = {
            'title': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter lifemark title',
            }),
            'link': forms.fields.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter related page link',
            }),
            'category': forms.fields.HiddenInput(),
            'state': forms.fields.Select(
                choices=CHOICES_STATE,
                attrs={'class': 'form-control'},
            ),
            'due_datehour': forms.fields.HiddenInput(),
            'rating': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '0 to 5 xs(xxxxx)'
            }),
            'tags': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter multiple tags with space separator'
            }),
            'desc': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'image_url': forms.fields.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter image url'
            }),
        }
        error_messages = {
            'title': {'required': "You need a valid title"}
        }

    def __init__(self, *args, **kwargs):
        super(LifemarkForm, self).__init__(*args, **kwargs)

    def clean_due_datehour(self):
        data = self.cleaned_data['due_datehour']
        if data and not DATEHOUR_PATTERN.match(data):
            raise forms.ValidationError(f"Invalid date hour format: {data}")

        return data

main/views.py
from collections import OrderedDict
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .models import Lifemark
from .forms import LifemarkForm
from core.models import LifemarkLineSearchData, LifemarkLineListData


DEFAULT_SEARCH_FIELDS = ('title',
                         'link',
                         'category',
                         'state',
                         'rating',
                         'tags',
                         'desc',
                         'image_url')


def get_distinct_categories():
    qset = Lifemark.objects.values('category').distinct()
    category_list = [e['category'] for e in qset]

    if '' not in category_list:
        category_list.append('')

    return sorted(category_list)


@login_required
def home_page(request):
    lifemarks = (Lifemark.objects
                         .order_by('-udate')[:10])
    existing_categories = get_distinct_categories()

    form = LifemarkForm()
    return render(request, 'home.html', {
        'lifemarks': lifemarks,
        'existing_categories': existing_categories,
        'form': form,
    })


@login_required
def search(request):
    param_keyword = request.GET.get('q')
    keywords = param_keyword.split()
    param_fields = request.GET.get('f')
    if param_fields:
        search_fields = param_fields.split()
    else:
        search_fields = ('title',
                         'link',
                         'category',
                         'state',
                         'rating',
                         'tags',
                         'desc',
                         'image_url')

    lifemarks_qs = Lifemark.objects.get_all_matches_on_any_fields(
        search_fields,
        keywords
    ).order_by('-udate')

    page_no = request.GET.get('page', 1)
    paginator = Paginator(lifemarks_qs, 10)
    try:
        page = paginator.page(page_no)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        # fallback to last_page
        page = paginator.page(paginator.num_pages)

    existing_categories = get_distinct_categories()

    form = LifemarkForm()
    return render(request, 'home.html', {
        'lifemarks': page,
        'existing_categories': existing_categories,
        'form': form,
    })


@method_decorator(login_required, name='dispatch')
class LifemarkSearchListView(ListView):
    model = Lifemark
    context_object_name = 'lifemarks'
    template_name = 'home.html'
    paginate_by = 10
    search_fields = DEFAULT_SEARCH_FIELDS

    def get_context_data(self, **kwargs):
        kwargs['existing_categories'] = get_distinct_categories()
        kwargs['form'] = LifemarkForm()

        paged_lifemarks = super().get_context_data()['page_obj']
        kwargs['lifemark_line_data'] = self.get_keywords_lines(
            list(paged_lifemarks),
            self.request.GET.get('q'),
            self.search_fields
        )

        return super().get_context_data(**kwargs)

    def get_queryset(self):
        keywords = self.request.GET.get('q')
        search_category = self.request.GET.get('c')
        search_state = self.request.GET.get('s')

        if keywords or search_category or search_state:
            queryset = Lifemark.objects.get_all_matches_on_any_fields(
                self.search_fields,
                search_category,
                search_state,
                keywords
            ).order_by('-udate')
        else:
            queryset = Lifemark.objects.all().order_by('-udate')
            self.search_by_line = []

        return queryset

    def get_keywords_lines(self, lifemarks, keywords_str, search_fieldnames=None):
        if not search_fieldnames:
            search_fieldnames = ()

        if keywords_str:
            keywords = keywords_str.split(' ')
        else:
            keywords = []

        search_line_data = OrderedDict()

        for lm in lifemarks:
            line_search_data = []
            for fieldname in search_fieldnames:
                field_lines = getattr(lm, fieldname).split('\r\n')
                for line_no, line in enumerate(field_lines):
                    for keyword in keywords:
                        if line and keyword.lower() in line:
                            match_line_data = LifemarkLineSearchData(fieldname, line_no, line)
                            if match_line_data not in line_search_data:
                                line_search_data.append(match_line_data)

            search_line_data[lm.id] = LifemarkLineListData(lm, line_search_data)

        return search_line_data


def new_lifemark(request):
    if request.method == 'POST':
        form = LifemarkForm(data=request.POST)
        if form.is_valid():
            form.save()

    return redirect(reverse_lazy('home'))


class CreateLifemarkView(CreateView):
    model = Lifemark
    form_class = LifemarkForm
    template_name = 'home.html'
    # below code failed w/ no reason i can catch!
    # success_url = reverse('home')
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.c_geo_lat = form['geo_lat'].value()
        form.instance.c_geo_lon = form['geo_lon'].value()
        form.instance.u_geo_lat = form['geo_lat'].value()
        form.instance.u_geo_lon = form['geo_lon'].value()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # add context data for no-redirect to success_url case
        #   - just like list view
        #     - but can't show prev list here
        #     - only set categories here
        #   - but 'form' is already set automatically by GCBV logic
        kwargs['existing_categories'] = get_distinct_categories()

        return super().get_context_data(**kwargs)

    '''
    def render_to_response(self, context, **response_kwargs):
        # for debug before response
        return super().render_to_response(context, response_kwargs)
        '''


def update_lifemark(request):
    if request.method == 'POST':
        target = Lifemark.objects.get(id=request.POST['id'])
        form = LifemarkForm(data=request.POST, instance=target)
        if form.is_valid():
            form.save()
    return redirect(reverse_lazy('home'))


class UpdateLifemarkView(UpdateView):
    model = Lifemark
    # fields = ('title', 'link', 'category', 'is_complete', 'due_datehour',
    #           'rating', 'tags', 'image_url')
    form_class = LifemarkForm
    template_name = 'home.html'
    # below code failed w/ no reason i can catch!
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.u_geo_lat = form['geo_lat'].value()
        form.instance.u_geo_lon = form['geo_lon'].value()

        return super().form_valid(form)


def show_map(request):
    latitude = request.GET.get('lat')
    longitude = request.GET.get('lon')

    return render(request, 'show_map.html', {
        'latitude': latitude,
        'longitude': longitude,
    })


class DeleteLifemarkView(DeleteView):
    model = Lifemark
    success_url = reverse_lazy('home')


class TestListView(ListView):
    model = Lifemark
    template_name = 'home.html'


class TestUpdateView(UpdateView):
    model = Lifemark


def test_view(request):
    return HttpResponse('<table><tr><td></td><td>title</td><td>0</td><td>aaa keyword</td></tr></table>')


def test_login(request):
    username = request.GET['username']
    password = request.GET['password']
    if not User.objects.filter(username=username).exists():
        User.objects.create_user(
            username=username,
            password=password
        )
    user = authenticate(request, username=username, password=password)
    login(request, user)

    return HttpResponse('create test login session')

main/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Lifemarks{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block javascript %}
        {% endblock javascript %}
    </head>
    <body>
        <button onclick="topFunction()" id="id_btn_top" title="Go to top">Top</button>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'home' %}">Lifemark</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Images</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Scraps</a></li>
            </ul>
            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="#" id="id_logged_in_user">{{ user.username }} logged in</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" id="id_btn_login" href="{% url 'login' %}"Login</a></li>
                    <li class="nav-item"><a class="nav-link" id="id_btn_signup" href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>

        <div class="container-fluid mt-2">
            {% block form %}
            {% endblock form %}

            {% block content %}
            {% endblock content %}
        </div>

        <script>
            window.onscroll = function() {scrollFunction()};

            function scrollFunction() {
                if (document.body.scrollTop > 20 ||
                    document.documentElement.scrollTop > 20) {
                    $('#id_btn_top')[0].style.display = "block"
                } else {
                    $('#id_btn_top')[0].style.display = "none"
                }
            }

            function topFunction() {
                document.body.scrollTop = 0
                document.documentElement.scrollTop = 0
            }
        </script>
        {% block init_javascript %}
        {% endblock init_javascript %}
    </body>
</html>

main/templates/home.html
{% extends 'base.html' %}

{% load static lifemark_filters %}

{% block javascript %}
    <script src="{% static 'js/desc_editor.js' %}"></script>
    <script>
        function get_detail_val(id, field_name) {
            return $('#row_'+id+'_'+field_name).text()
        }
        function set_form_data($form, id, field_name, val) {
            if (val)
                $form.find('#id_'+field_name).val(val)
            else
                $form.find('#id_'+field_name).val(get_detail_val(id, field_name))
        }
        function lpad(str, pad, len) {
            padstr = ''
            while (padstr.length < len)
                padstr += pad
            constr = padstr + str
            return constr.substring(constr.length - len)
        }
        function submit_form(form) {
            $form = $(form)
            fill_form_hiddens($form)

            get_geo_location($form, function() {
                console.log($form.find('#id_geo_lat').val())
                form.submit()
            })
            
            return false
        }
        function submit_category_search(category) {
            var $form = $('#id_search_form')
            $form.find('#id_hdn_search_category').val(category)

            return true
        }
        function submit_state_search(state) {
            var $form = $('#id_search_form')
            $form.find('#id_hdn_search_state').val(state)

            return true
        }
        function get_geo_location($form, callback) {
            var $geo_lat = $form.find('#id_geo_lat')
            var $geo_lon = $form.find('#id_geo_lon')

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(pos) {
                        var lat = pos.coords.latitude.toFixed(6)
                        var lon = pos.coords.longitude.toFixed(6)

                        $geo_lat.val(lat)
                        $geo_lon.val(lon)

                        callback()
                    },
                    function() {
                        $geo_lat.val(0)
                        $geo_lon.val(0)

                        callback()
                    }
                )
            } else {
                $geo_lat.val(0)
                $geo_lon.val(0)

                callback()
            }
        }
        function make_datehour(date, hour) {
            return date + ' ' + hour
        }
        function get_due_date_input($form) {
            if ($form.attr('id') == 'id_update_form') {
                return $('#id_update_due_date')
            } else {
                return $('#id_due_date')
            }
        }
        function fill_form_hiddens($form) {
            var $category_hidden = $form.find('#id_category')
            var $category_txt = $form.find('#id_category_txt')
            var $category_sel = $form.find('#id_category_sel')
            if ($category_txt.val()) 
                $category_hidden.val($category_txt.val())
            else
                $category_hidden.val($category_sel.val())

            var $due_date = get_due_date_input($form)
            var $due_hour = $form.find('#id_due_hour')
            if ($due_date.val()) {
                var $due_datehour = $form.find('#id_due_datehour')
                var datehour = make_datehour($due_date.val(), lpad($due_hour.val(), '0', 2))
                $due_datehour.val(datehour)
            }
        }
        function fill_form_w_detail($form, id) {
            set_form_data($form, id, 'title')
            set_form_data($form, id, 'link')
            set_form_data($form, id, 'state')

            var category = get_detail_val(id, 'category')
            $form.find('#id_category_sel').val(category)

            // due_datehour format=2018-01-02 03
            var due_datehour = get_detail_val(id, 'due_datehour')
            due_date = due_datehour.substring(0, 10)
            due_hour = due_datehour.substring(10) * 1 + ''
            // set_form_data($form, id, 'due_date', due_date)  // can't use same id for datepicker target input, so try below way
            get_due_date_input($form).val(due_date)
            set_form_data($form, id, 'due_hour', due_hour)

            set_form_data($form, id, 'rating')
            set_form_data($form, id, 'tags')
            set_form_data($form, id, 'desc')
            set_form_data($form, id, 'image_url')
        }
        function edit(e, id) {
            e.stopPropagation()

            show_form('update')
            
            var $update_form = $('#id_update_form')
            fill_form_w_detail($update_form, id)

            $update_form.attr('action', 'update/' + id + '/')

            $('html, body').scrollTop(0)
        }
        function del(id) {
            if (!confirm('Want to delete?'))
                return

            var $form = $('#id_del_form')
            $form.attr('action', 'delete/' + id + '/')
            $form[0].submit()
        }
        function copy_lifemark(id) {
            fill_form_w_detail($('#id_new_form'), id)

            $('html, body').scrollTop(0)
        }
        function get_active_form() {
            if ($('#id_new_form').is(':visible'))
                return $('#id_new_form')
            else
                return $('#id_update_form')
        }
        function toggle_desc_editor() {
            editor_module.set_editor(get_active_form().find('#id_desc'))
        }
        function toggle_due_date_picker() {
            get_due_date_input(get_active_form()).datepicker({dateFormat: 'yy-mm-dd'})
        }
        function show_form(form_type) {
            var $new_form = $('#id_new_form')
            var $update_form = $('#id_update_form')

            if (form_type == 'new') {
                $new_form.show()
                $update_form.hide()
            } else {
                $new_form.hide()
                $update_form.show()
            }

            toggle_desc_editor()
            toggle_due_date_picker()
        }
        function goto_detail(key, line) {
            var $row = $('#row_'+key)
            if (! line) {
                $row.get(0).scrollIntoView()
            } else {
                var desc_pre = $row.find('pre')
                
                var pre_top = desc_pre.offset().top
                var pre_height = desc_pre.height()
                var total_line = desc_pre.html().split(/\n/).length

                var line_height = pre_height / total_line
                var target_pixcel = pre_top + line * line_height

                window.scrollTo(0, target_pixcel)
            }
        }
    </script>
{% endblock javascript %}

{% block form %}
    <form class="form-horizontal" id="id_new_form" method="POST" onsubmit="return submit_form(this)" action="{% url 'new' %}">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-12">
                <button type="submit" id="id_btn_new" class="btn btn-primary">Add Lifemark</button>
            </div>
        </div>
        {% include 'includes/lifemark_form.html' with is_update_form=False %}
    </form>
    <form class="form-horizontal" id="id_update_form" method="POST" onsubmit="return submit_form(this)" action="">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-12">
                <button type="submit" id="id_btn_update" class="btn btn-primary">Update Lifemark</button>
                <button class="btn btn-primary" onclick="show_form('new')">Cancel</button>
            </div>
        </div>
        {% include 'includes/lifemark_form.html' with is_update_form=True %}
    </form>
    {% if form.errors %}
        <div class="has-error">
            <span class="help-block">
                {{ form.errors }}
            </span>
        </div>
    {% endif %}
{% endblock form %}

{% block content %}
    <form id="id_search_form" method="GET" action="{% url 'search' %}">
        <div class="row bg-primary" style="padding-top: .5em; padding-bottom: .5em">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-primary btn-md" id="id_btn_search">Search</button>
                <button type="submit" class="btn btn-primary btn-md" id="id_btn_search_todo" onclick="return submit_state_search('todo')">Search Todo</button>
                <button type="submit" class="btn btn-primary btn-md" id="id_btn_search_working" onclick="return submit_state_search('working')">Search Working</button>
                <button type="submit" class="btn btn-primary btn-md" id="id_btn_search_ref" onclick="return submit_category_search('ref')">Search Ref</button>
            </div>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="id_txt_search" name="q">
                <input type="hidden" id="id_hdn_search_category" name="c" />
                <input type="hidden" id="id_hdn_search_state" name="s" />
            </div>
        </div>
    </form>

    <form id="id_del_form" method="POST" action="">
        {% csrf_token %}

        <table id="id_recent_list" class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Category</th>
                    <th colspan="2">Title</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for key, line_data in lifemark_line_data.items %}
                    <tr onclick="goto_detail({{ key }})" class="{{ line_data.lifemark|td_class }}">
                        <td>{{ key }}</td>
                        <td>{{ line_data.lifemark.category }}</td>
                        <td colspan="2">
                            {{ line_data.lifemark.title }}
                        </td>
                        <td>
                            <button id="id_list_btn_edit_{{ key }}" type="button" class="btn btn-primary btn-sm" onclick="edit(event, {{ key }})">Edit</button>
                            <button id="id_list_btn_del_{{ key }}" type="button" class="btn btn-primary btn-sm" onclick="del({{ key }})">Del</button>
                        </td>
                    </tr>
                    {% for line_search_data in line_data.lines %}
                        <tr onclick="goto_detail({{ key }}, {{ line_search_data.line_no }})">
                            <td></td>
                            <td>{{ line_search_data.field }}</td>
                            <td>{{ line_search_data.line_no }}</td>
                            <td>{{ line_search_data.match_line }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
        {% include 'includes/range_pagination.html' %}

        <table id="id_detail_list" class="table">
            <tbody>
                {% for lifemark in lifemarks %}
                    <tr id="row_{{ lifemark.id }}" class="{{ lifemark|td_class }}">
                        <td>
                            {% include 'includes/lifemark_detail.html' %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include 'includes/range_pagination.html' %}

    </form>
{% endblock content %}

{% block init_javascript %}
    <script>
        $('#id_update_form').hide()

        $(function() {
            $('#id_due_date').datepicker({dateFormat: 'yy-mm-dd'})
            $('#id_update_due_date').datepicker({dateFormat: 'yy-mm-dd'})
        })

        toggle_desc_editor()
    </script>
{% endblock init_javascript %}

main/templates/show_map.html
<!DOCTYPE html>
<html>
    <head>
        <title>Simple Map</title>
        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="utf-8">
        <style>
            /* Always set the map height explicitly to define the size of the div
            * element that contains the map. */
            #map {
                height: 100%;
            }
            /* Optional: Makes the sample page fill the window. */
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
        </style>
    </head>
    <body>
        <h1><a href="{% url 'home' %}">Go to Main</a></h1>
        <div id="map"></div>
        <script>
        var map;
        function initMap() {
            var pos = {lat: {{ latitude }}, lng: {{ longitude }}};

            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 18,
                center: pos
            });

            var marker = new google.maps.Marker({
                position: pos,
                map: map,
                title: 'Lifemarked!'
            });
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByfp3pOhCGXaUN7cAnpp5jn_V6fRqlmJk&callback=initMap" async defer></script>
    </body>
</html>